//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoToText.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlaylistId {
            get {
                return ((string)(this["PlaylistId"]));
            }
            set {
                this["PlaylistId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoId {
            get {
                return ((string)(this["VideoId"]));
            }
            set {
                this["VideoId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputPath {
            get {
                return ((string)(this["OutputPath"]));
            }
            set {
                this["OutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApiKey {
            get {
                return ((string)(this["ApiKey"]));
            }
            set {
                this["ApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogText {
            get {
                return ((string)(this["LogText"]));
            }
            set {
                this["LogText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPlaylistChecked {
            get {
                return ((bool)(this["IsPlaylistChecked"]));
            }
            set {
                this["IsPlaylistChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Tôi là một Phật tử theo truyền thống Phật giáo Nguyên thủy Theravada đang ghi chép bài giảng của Sư. Hãy thực hiện các nhiệm vụ sau với file âm thanh đính kèm:
1. Chuyển đổi toàn bộ nội dung âm thanh thành văn bản. 
2. Loại bỏ các từ không cần thiết thường xuất hiện trong văn nói như từ đệm, từ lặp, hoặc các cụm từ trong văn nói. 
3. Sắp xếp và định dạng lại nội dung thành các đoạn văn có cấu trúc rõ ràng, mạch lạc. 
4. Đảm bảo kết quả cuối cùng dễ đọc và dễ hiểu nhất có thể, trong khi vẫn giữ nguyên ý nghĩa chính của nội dung gốc. 
5. Nếu có bất kỳ thuật ngữ hoặc khái niệm nào liên quan đến Phật giáo Nguyên thủy Theravada, hãy chú ý giữ nguyên và sử dụng chính xác.")]
        public string Prompt {
            get {
                return ((string)(this["Prompt"]));
            }
            set {
                this["Prompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gemini-1.5-pro-002")]
        public string SelectedModel {
            get {
                return ((string)(this["SelectedModel"]));
            }
            set {
                this["SelectedModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPayAsYouGo {
            get {
                return ((bool)(this["IsPayAsYouGo"]));
            }
            set {
                this["IsPayAsYouGo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal StartIndex {
            get {
                return ((decimal)(this["StartIndex"]));
            }
            set {
                this["StartIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal EndIndex {
            get {
                return ((decimal)(this["EndIndex"]));
            }
            set {
                this["EndIndex"] = value;
            }
        }
    }
}
